# Generated by Django 5.1.5 on 2026-03-20 14:28

import django.db.models.deletion
import django_enumfield.db.fields
import problems.models.preparation
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage', models.TextField()),
                ('kind', django_enumfield.db.fields.EnumField(enum=problems.models.preparation.PreparationKind)),
                ('status', django_enumfield.db.fields.EnumField(default=0, enum=problems.models.preparation.PreparationStatus)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_location', models.TextField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PolygonPreparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pkg_storage', models.TextField()),
                ('preparation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='problems.preparation')),
            ],
        ),
        migrations.AddField(
            model_name='preparation',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='problems.problem'),
        ),
    ]
