"""
Django settings for taskrunner project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-z2f9#&lmzp_u*@v9liig1(cmnuw2heshzz2n1vj)yeszi)t^*n'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'daphne',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'judge',
    'sandbox',
    'storecli',
    'submit',
    'problems',
    'storage',
    'rules',
    'ccs'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'taskrunner.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'taskrunner.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

AUTHENTICATION_BACKENDS = (
    'rules.permissions.ObjectPermissionBackend',
    'django.contrib.auth.backends.ModelBackend',
)

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'






from storecli.base import BaseStorageClient
from opentelemetry.instrumentation.celery import CeleryInstrumentor
from celery import Celery

MAX_NB_SANDBOX = 5

DEFAULT_TIME_LIMIT = 1.0
DEFAULT_WALL_TIME  = 1.0
DEFAULT_EXTRA_TIME = 0.1
DEFAULT_MEMORY_KB  = 256 * 1024 # 256 MB

SANDBOX_RESULT_FOLDER = "/app/results"

PYTHON_EXECUTABLE = "/usr/bin/python3"
CXX_COMPILER = "/usr/bin/g++"
JAVA_COMPILER = "/usr/bin/javac"
JAR_COMPILER = "/usr/bin/jar"
JAVA_EXECUTABLE = "/usr/bin/java"
JVM_DIRECTORIES = [ "/etc/alternatives", "/usr/lib/jvm", "/etc/java-21-openjdk/" ]

STORAGE_CLIENT  = BaseStorageClient()
PROBLEM_STORAGE_LOCATION = "/app/problems"
STORAGE_SERVER_LOCATION  = "/app/storage/server"

CELERY_BACKEND = "redis://localhost:6379/0"
CELERY_BROKER  = "pyamqp://guest@localhost//"

MAX_LEN_ERROR_MESSAGE = 1024
MAX_TESTS_PER_BATCH = 8

WALL_TIME_ADDITIONAL = 0.1

USE_CGROUPS = False

ASGI_APPLICATION = "taskrunner.asgi.application"

EVENTFEED_HEARTBEET_TIME = 30

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}
