"""
Django settings for taskrunner project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

from storecli.cache import CacheClient
from storecli.network import NetworkClient

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-z2f9#&lmzp_u*@v9liig1(cmnuw2heshzz2n1vj)yeszi)t^*n'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "storage.polympiads.ch"
]


# Application definition

INSTALLED_APPS = [
    'daphne',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'judge',
    'sandbox',
    'storecli',
    'submit',
    'problems',
    'storage',
    'rules',
    'ccs',
    "printing"
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'taskrunner.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB', 'postgres'),
        'USER': os.environ.get('POSTGRES_USER', 'postgres'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'postgres'),
        'HOST': os.environ.get('POSTGRES_HOST', 'postgresql'), # Use the service name from compose
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = (
    'rules.permissions.ObjectPermissionBackend',
    'django.contrib.auth.backends.ModelBackend',
)


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'






from storecli.base import BaseStorageClient
from opentelemetry.instrumentation.celery import CeleryInstrumentor
from opentelemetry.instrumentation.requests import RequestsInstrumentor
from celery import Celery

CeleryInstrumentor().instrument()
RequestsInstrumentor().instrument()

MAX_NB_SANDBOX = 5

DEFAULT_TIME_LIMIT = 1.0
DEFAULT_WALL_TIME  = 1.0
DEFAULT_EXTRA_TIME = 0.1
DEFAULT_MEMORY_KB  = 256 * 1024 # 256 MB

BASE_STORAGE_DIR = "/var/lib/taskrunner"

SANDBOX_RESULT_FOLDER = BASE_STORAGE_DIR + "/results"

PYTHON_EXECUTABLE = "/usr/bin/python3"
CXX_COMPILER = "/usr/bin/g++"
JAVA_COMPILER = "/usr/bin/javac"
JAR_COMPILER = "/usr/bin/jar"
JAVA_EXECUTABLE = "/usr/bin/java"
JVM_DIRECTORIES = [ "/etc/alternatives", "/usr/lib/jvm", "/etc/java-21-openjdk/" ]

TEMPDIR_STORAGE_LOCATION = BASE_STORAGE_DIR + "/tmp"
PROBLEM_STORAGE_LOCATION = BASE_STORAGE_DIR + "/problems"
STORAGE_SERVER_LOCATION  = BASE_STORAGE_DIR + "/storage/server"
STORAGE_CLIENT_LOCATION  = BASE_STORAGE_DIR + "/storage/client"
STORAGE_CLIENT  = CacheClient( NetworkClient( "http://storage.polympiads.ch:8000", STORAGE_CLIENT_LOCATION ) )

ROOT_URLCONF = 'storage.urls'

REDIS_HOST = os.environ.get("REDIS_HOST", "redis://backend.polympiads.ch:6379/")
RABBITMQ_HOST = os.environ.get("RABBITMQ_HOST", "pyamqp://guest@broker.polympiads.ch//")

CELERY_BACKEND = REDIS_HOST + "0"
CELERY_BROKER  = RABBITMQ_HOST

MAX_PRINT_SIZE = 32 * 1024
MAX_PRINT_WORD_SIZE = 80
MAX_PRINT_LINE_COUNT = 512

MAX_SUBMISSION_SIZE = 32 * 1024
MAX_LEN_ERROR_MESSAGE = 1024
MAX_TESTS_PER_BATCH = 8

WALL_TIME_ADDITIONAL = 0.1

USE_CGROUPS = False

ASGI_APPLICATION = "taskrunner.asgi.application"

EVENTFEED_HEARTBEET_TIME = 30

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [REDIS_HOST + "1"],
        },
    },
}
