# Generated by Django 5.1.5 on 2026-03-24 09:05

import balloons.models
import django.db.models.deletion
import django_enumfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ccs', '0002_clarification'),
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Balloon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', django_enumfield.db.fields.EnumField(default=0, enum=balloons.models.BalloonStatus)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ccs.contest')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='problems.problem')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
