# Generated by Django 5.1.5 on 2026-03-20 14:28

import ccs.models.contest
import ccs.models.visible
import datetime
import django.db.models.deletion
import django_enumfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', django_enumfield.db.fields.EnumField(enum=ccs.models.visible.Visibility)),
                ('name', models.CharField(max_length=64)),
                ('formal_name', models.CharField(default=None, max_length=64, null=True)),
                ('start_time', models.DateTimeField(default=None, null=True)),
                ('countdown_pause_time', models.DurationField(default=None, null=True)),
                ('duration', models.DurationField()),
                ('scoreboard_freeze_duration', models.DurationField(default=datetime.timedelta(0), null=True)),
                ('scoreboard_thaw_time', models.DateTimeField(default=None, null=True)),
                ('penalty_time', models.DurationField()),
                ('started', models.DateTimeField(default=None, null=True)),
                ('frozen', models.DateTimeField(default=None, null=True)),
                ('ended', models.DateTimeField(default=None, null=True)),
                ('thawed', models.DateTimeField(default=None, null=True)),
                ('finalized', models.DateTimeField(default=None, null=True)),
                ('end_of_updates', models.DateTimeField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContestAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', django_enumfield.db.fields.EnumField(enum=ccs.models.contest.ContestRole)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccs.contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'contest')},
            },
        ),
        migrations.AddField(
            model_name='contest',
            name='accounts',
            field=models.ManyToManyField(related_name='contest_accounts', through='ccs.ContestAccount', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ContestProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ccs.contest')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='problems.problem')),
            ],
            options={
                'unique_together': {('problem', 'contest')},
            },
        ),
        migrations.AddField(
            model_name='contest',
            name='problems',
            field=models.ManyToManyField(related_name='contest_problems', through='ccs.ContestProblem', to='problems.problem'),
        ),
        migrations.CreateModel(
            name='EventFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', django_enumfield.db.fields.EnumField(enum=ccs.models.visible.Visibility)),
                ('raw_payload', models.TextField()),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ccs.contest')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
