# Generated by Django 5.1.5 on 2026-03-24 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccs', '0001_initial'),
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clarification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('time', models.DateTimeField()),
                ('broadcast', models.BooleanField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clr_author', to=settings.AUTH_USER_MODEL)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ccs.contest')),
                ('problem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='problems.problem')),
                ('reply_to', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replies', to='ccs.clarification')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clr_original_team', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
