# Generated by Django 5.1.5 on 2026-03-20 14:28

import django.db.models.deletion
import django_enumfield.db.fields
import judge.languages
import submit.models.status
import submit.models.verdict
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ccs', '0001_initial'),
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', django_enumfield.db.fields.EnumField(default=0, enum=submit.models.status.SubmissionStatus)),
                ('verdict', django_enumfield.db.fields.EnumField(default=-1, enum=submit.models.verdict.SubmissionVerdict)),
                ('language', django_enumfield.db.fields.EnumField(enum=judge.languages.LanguageKind)),
                ('code_location', models.TextField()),
                ('exec_location', models.TextField()),
                ('first_wrong_test', models.IntegerField(default=-1)),
                ('contest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ccs.contest')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='problems.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
