# Generated by Django 5.1.5 on 2026-03-24 09:05

import django.db.models.deletion
import django_enumfield.db.fields
import printing.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ccs', '0002_clarification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestPrint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', django_enumfield.db.fields.EnumField(default=0, enum=printing.models.PrintStatus)),
                ('code_location', models.TextField()),
                ('simple_error', models.TextField(default=None, null=True)),
                ('pdf_location', models.TextField(default=None, null=True)),
                ('err_location', models.TextField(default=None, null=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ccs.contest')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
